### ISSUE TITLE
Automatically use swift version if it is the first version of swift downloaded

### ISSUE THREAD

**Issue by adam-fowler** [patrickfreed/swiftly#30]
If no other versions of swift are downloaded then `swiftly install` should also call `use` on the downloaded version of swift

**Comment by patrickfreed** [comment]
This is the current behavior already, see https://github.com/patrickfreed/swiftly/blob/main/Tests/SwiftlyTests/InstallTests.swift#L224 for a test of it. Have you observed this not working properly?

**Comment by adam-fowler** [comment]
sorry yeah it does seem to be
